### ISSUE TITLE
Worst deployment experience

### ISSUE THREAD

**Issue by shabarkin** [paradigmxyz/paradigm-ctf-2021#22]
You would better provide the tutorial to deploy all these stuff. I have checked a couple of the scripts to figure out how it is working. I would say I need to spend more deploying than solving. It is not normal. I hope you will fix that.

**Comment by othernamesweretaken** [comment]
Hi there,
Were you able to solve issues using build command? 
especially "import mp from *"

**Comment by shabarkin** [comment]
> Hi there,
> 
> Were you able to solve issues using build command? 
> 
> especially "import mp from *"
> 
> 

Hello, 
Yeah, you need to add the path where the mpwn module is located to PYTHONPATH

**Comment by othernamesweretaken** [comment]
I tried to change it in docker file and in my ENV variables too. 
Can share the exact path you changed ? 
I am missing something here

**Comment by ghost** [comment]
Updated the README to be a little clearer
