### ISSUE TITLE
"failed to launch instance! please try again"

### ISSUE THREAD

**Issue by nikitastupin** [paradigmxyz/paradigm-ctf-2021#3]
Hi 👋 Thanks for the challenges and for the infrastructure for custom challenges! The code is great, learned a lot from it (reminded me the times when I just started poking around Linux).

When I've built and started `babysandbox` challenge I've got the "failed to launch instance! please try again" error. After some poking I've found out that [it's caused by NodeJS 17](https://github.com/webpack/webpack/issues/14532#issuecomment-947012063). Basically, "ganache-cli" just won't run.

```
root@a41b14c2f092:/# ganache-cli 
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
```

So, in case if someone else is experiencing the same problem - to fix it set `NODE_OPTIONS` to `--openssl-legacy-provider`.

```diff
diff --git a/eth_challenge_base/Dockerfile b/eth_challenge_base/Dockerfile
index c28eea9..3d213b4 100644
--- a/eth_challenge_base/Dockerfile
+++ b/eth_challenge_base/Dockerfile
@@ -15,3 +15,4 @@ COPY 98-start-gunicorn /startup
 
 COPY eth_sandbox /usr/lib/python/eth_sandbox
 ENV PYTHONPATH /usr/lib/python
+ENV NODE_OPTIONS --openssl-legacy-provider
```

**Comment by man715** [comment]
Nice. Thank you for this. Just curious, how did you track that down?

**Comment by nikitastupin** [comment]
As far as I remember I've just googled the error and found the answer in StackOverflow 😅
